package report

import (
	"fmt"
	"time"

	"loot/internal/hash"
	"loot/internal/offload"

	"github.com/go-pdf/fpdf"
)

// GeneratePDF creates a PDF report for the offload operation
func GeneratePDF(path string, o *offload.Offloader, startTime, endTime time.Time) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(40, 10, "LOOT - Offload Report")
	pdf.Ln(12)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(40, 10, fmt.Sprintf("Date: %s", time.Now().Format(time.RFC1123)))
	pdf.Ln(8)

	jobName := o.Config.JobName
	if jobName != "" {
		pdf.SetFont("Arial", "B", 12)
		pdf.Cell(40, 10, fmt.Sprintf("Job Name: %s", jobName))
		pdf.Ln(6)
	}

	// Metadata Line
	meta := ""
	if o.Config.Camera != "" {
		meta += fmt.Sprintf("Camera: %s    ", o.Config.Camera)
	}
	if o.Config.Reel != "" {
		meta += fmt.Sprintf("Reel: %s", o.Config.Reel)
	}

	if meta != "" {
		pdf.SetFont("Arial", "", 12)
		pdf.Cell(40, 10, meta)
		pdf.Ln(10)
	} else {
		if jobName != "" {
			pdf.Ln(4)
		} else {
			pdf.Ln(2)
		}
	}

	// File Details
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(40, 10, "Job Details")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(40, 8, fmt.Sprintf("Source:      %s", o.Source))
	pdf.Ln(6)
	for i, dst := range o.Destinations {
		pdf.Cell(40, 8, fmt.Sprintf("Dest %d:      %s", i+1, dst))
		pdf.Ln(6)
	}
	pdf.Ln(6)
	pdf.Cell(40, 8, fmt.Sprintf("Files:       %d", len(o.Files)))
	pdf.Ln(6)

	// Calculate total size from files list to be accurate
	var totalSize int64
	for _, f := range o.Files {
		totalSize += f.Size
	}
	pdf.Cell(40, 8, fmt.Sprintf("Total Size:  %s", offload.FormatBytes(uint64(totalSize))))
	pdf.Ln(8)

	// Transfer Stats
	duration := endTime.Sub(startTime)
	seconds := duration.Seconds()
	speedBps := float64(totalSize) / seconds

	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(40, 10, "Transfer Statistics")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(40, 8, fmt.Sprintf("Start Time: %s", startTime.Format("15:04:05")))
	pdf.Ln(6)
	pdf.Cell(40, 8, fmt.Sprintf("End Time:   %s", endTime.Format("15:04:05")))
	pdf.Ln(6)
	pdf.Cell(40, 8, fmt.Sprintf("Duration:   %v", duration.Round(time.Second)))
	pdf.Ln(6)
	pdf.Cell(40, 8, fmt.Sprintf("Avg Speed:  %s/s", offload.FormatBytes(uint64(speedBps))))
	pdf.Ln(8)

	// Verification
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(40, 10, "Verification (xxHash)")
	pdf.Ln(8)

	// Check if we have a single root hash (single file) or need to list files
	if o.SourceHash != (hash.HashResult{}) && o.SourceHash.String() != "" {
		// Single file or root hash available
		pdf.SetFont("Arial", "", 10)
		pdf.Cell(40, 10, fmt.Sprintf("Source Hash: %s", o.SourceHash))
		pdf.Ln(6)
		pdf.Cell(40, 10, fmt.Sprintf("Dest Hash:   %s", o.DestHash))
		pdf.Ln(8)

		if o.SourceHash == o.DestHash {
			pdf.SetFont("Arial", "B", 12)
			pdf.SetTextColor(0, 128, 0) // Green
			pdf.Cell(40, 10, "STATUS: VERIFIED MATCH")
		} else {
			pdf.SetFont("Arial", "B", 12)
			pdf.SetTextColor(255, 0, 0) // Red
			pdf.Cell(40, 10, "STATUS: CHECKSUM MISMATCH")
		}
	} else {
		// List files and their hashes (and metadata)
		pdf.SetFont("Arial", "B", 9)
		pdf.Cell(55, 8, "File")
		pdf.Cell(20, 8, "Back/Codec")
		pdf.Cell(20, 8, "Res")
		pdf.Cell(15, 8, "FPS")
		pdf.Cell(25, 8, "TC")
		pdf.Cell(20, 8, "Dur")
		pdf.Cell(35, 8, "Hash")
		pdf.Ln(8)

		pdf.SetFont("Arial", "", 8)
		for _, f := range o.Files {
			// Get relative path shortened
			relPath := f.RelPath
			if len(relPath) > 30 {
				relPath = "..." + relPath[len(relPath)-27:]
			}

			// Metadata
			codec := "-"
			res := "-"
			fps := "-"
			tc := "-"
			dur := "-"

			if f.Metadata != nil {
				codec = f.Metadata.Codec
				res = f.Metadata.Resolution
				fps = f.Metadata.FrameRate
				tc = f.Metadata.Timecode
				dur = f.Metadata.Duration

				// Truncate codec if too long
				if len(codec) > 10 {
					codec = codec[:10]
				}
			}

			hashStr := f.Hash.String()
			// Shorten hash for display if needed or keep full?
			// xxHash is 16 chars, MD5 is 32. 35mm width fits ~18 chars at size 8?
			// Let's take first 16 chars
			if len(hashStr) > 16 {
				hashStr = hashStr[:16] + "..."
			}

			pdf.Cell(55, 6, relPath)
			pdf.Cell(20, 6, codec)
			pdf.Cell(20, 6, res)
			pdf.Cell(15, 6, fps)
			pdf.Cell(25, 6, tc)
			pdf.Cell(20, 6, dur)
			pdf.Cell(35, 6, hashStr)
			pdf.Ln(6)
		}

		pdf.Ln(6)
		if len(o.Files) > 0 {
			pdf.SetFont("Arial", "B", 12)
			pdf.SetTextColor(0, 128, 0) // Green
			pdf.Cell(40, 10, "STATUS: ALL FILES VERIFIED")
		}
	}
	pdf.SetTextColor(0, 0, 0) // Reset

	// footer
	pdf.SetY(-15)
	pdf.SetFont("Arial", "I", 8)
	pdf.Cell(0, 10, fmt.Sprintf("Generated by LOOT on %s", time.Now().Format("2006-01-02")))

	return pdf.OutputFileAndClose(path)
}
