package report

import (
	"fmt"
	"time"

	"loot/internal/offload"

	"github.com/go-pdf/fpdf"
)

// GeneratePDF creates a PDF report for the offload operation
func GeneratePDF(path string, o *offload.Offloader, startTime, endTime time.Time) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(40, 10, "LOOT - Offload Report")
	pdf.Ln(12)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(40, 10, fmt.Sprintf("Date: %s", time.Now().Format(time.RFC1123)))
	pdf.Ln(10)

	// File Details
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(40, 10, "File Details")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(40, 10, fmt.Sprintf("Source: %s", o.Source))
	pdf.Ln(6)
	pdf.Cell(40, 10, fmt.Sprintf("Destination: %s", o.Destination))
	pdf.Ln(8)

	// Transfer Stats
	duration := endTime.Sub(startTime)
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(40, 10, "Transfer Statistics")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(40, 10, fmt.Sprintf("Start Time: %s", startTime.Format(time.Kitchen)))
	pdf.Ln(6)
	pdf.Cell(40, 10, fmt.Sprintf("End Time: %s", endTime.Format(time.Kitchen)))
	pdf.Ln(6)
	pdf.Cell(40, 10, fmt.Sprintf("Duration: %v", duration))
	pdf.Ln(8)

	// Verification
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(40, 10, "Verification (xxHash)")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 10) // Smaller font for hashes
	pdf.Cell(40, 10, fmt.Sprintf("Source Hash: %s", o.SourceHash))
	pdf.Ln(6)
	pdf.Cell(40, 10, fmt.Sprintf("Dest Hash:   %s", o.DestHash))
	pdf.Ln(8)

	if o.SourceHash == o.DestHash {
		pdf.SetFont("Arial", "B", 12)
		pdf.SetTextColor(0, 128, 0) // Green
		pdf.Cell(40, 10, "STATUS: VERIFIED MATCH")
	} else {
		pdf.SetFont("Arial", "B", 12)
		pdf.SetTextColor(255, 0, 0) // Red
		pdf.Cell(40, 10, "STATUS: CHECKSUM MISMATCH")
	}
	pdf.SetTextColor(0, 0, 0) // Reset

	// footer
	pdf.SetY(-15)
	pdf.SetFont("Arial", "I", 8)
	pdf.Cell(0, 10, fmt.Sprintf("Generated by LOOT on %s", time.Now().Format("2006-01-02")))

	return pdf.OutputFileAndClose(path)
}
